name: Docker Image CI

on:
  push:
    branches: [ "feat/2.0.0" ]
  pull_request:
    branches: [ "feat/2.0.0" ]

jobs:
  
  test:
    runs-on: ubuntu-latest
    steps:
    - name: rust-cargo
      uses: actions-rs/cargo@v1.0.1
      with:
        command: test --release

  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: eziotobioli/test-github:latest
